Repository GradeDe-rtype/Client, pull requests merged in 2025-01, with the labels that each got.

#3 2 fix boss ennemy visual
  src/Game/Entity/Enemy/Enemy.cpp
  src/Game/Entity/Enemy/Enemy.hpp
Labels: Visual fix

#10 7 enchancementgame add shape for bonus and weapons
  src/Communication/Commands/Commands.cpp
  src/Game/Entity/Enemy/Enemy.cpp
  src/Game/Entity/Enemy/Enemy.hpp
Labels: fix, game

#5 [+] add(testing): build Unit Tests and add Enemy class tests
  CMakeLists.txt
  assets/lang/en.json
  assets/lang/fr.json
  src/Communication/Commands/Commands.cpp
  src/Game/Components/EndIndicator/EndIndicator.cpp
  src/Game/Entity/Enemy/Enemy.cpp
  src/Game/Entity/Enemy/Enemy.hpp
  src/Game/Entity/Player/Player.cpp
  src/Game/Entity/Player/Player.hpp
  src/Game/Scenes/Game/GameScene.cpp
  src/Game/Scenes/Game/GameScene.hpp
  src/Game/Scenes/Menu/MenuScene.hpp
  src/Ressources/Ressources.cpp
  src/Ressources/Ressources.hpp
  tests/CMakeLists.txt
  tests/GraphicalTests.cpp
Labels: feature, testing

#15 UnitTest/Graphical
  .gitignore
  bin/run_tests.sh
  tests/CMakeLists.txt
  tests/GraphicalTests.cpp
Labels: enhancement, testing
